[GLOBAL]
pants_version = "2.28.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.awslambda.python",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
]

[python]
enable_resolves=true
interpreter_constraints = ["CPython==3.11.*"]

